server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-customers
          uri: lb://bank-customers
          predicates:
          - Path=/customer/**
        - id: bank-products-saving-accounts
          uri: lb://bank-products-saving-accounts
          predicates:
          - Path=/savingAccounts/**
        - id: bank-products-fixed-accounts
          uri: lb://bank-products-fixed-accounts
          predicates:
          - Path=/fixedAccounts/**
        - id: bank-products-current-accounts
          uri: lb://bank-products-current-accounts
          predicates:
          - Path=/currentAccounts/**
        - id: bank-yanki
          uri: lb://bank-yanki
          predicates:
          - Path=/yanki/**
        - id: bank-bootcoin
          uri: lb://bank-bootcoin
          predicates:
          - Path=/bootcoin/**